### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by tooky** [SmartBear/react-gherkin-editor#10]
I had a little play last night to plug the react-gherkin-editor into the [gherkin-editor](https://github.com/SmartBear/gherkin-editor), and had a few difficulties.

First. The readme says to use yarn add git+ssh … it doesn’t work, because you have to build the package to have it as usable npm package… so I copied the tar.gz into the repo and installed it as file… that sort of worked. I could install the packag, but seemed to be brittle and would give errors if I tried to install another package afterwards. I don't know if this is about yarn workspaces which they use on that project?

Once installed, the react-gherkin-editor I hit some dependency issues. `styled-components` and `atlaskit/select`. I don't know enough about `styled-components` and the gherkin-editor to know if this will be an issue. But I guess relying on atlaskit inside this will be a problem for tools outside of jira.

FYI @mattwynne @jbpros @cbohiptest

**Comment by TimotheeVille** [comment]
Hi @tooky, the README should now be up-to-date. 
The NPM package is available from the npm public registry, it should prevent you to download the archive.

Also, we removed all @atlaskit dependencies. Can you please retry and let me know?

**Comment by cbohiptest** [comment]
The react-gherkin-editor is used in [gherkin-editor](https://github.com/SmartBear/gherkin-editor)  since commit https://github.com/SmartBear/gherkin-editor/commit/a694da0080d2fef8aad0f896134362e9da7007e7
