### ISSUE TITLE
Add `onGherkinDocumentChange` prop

### ISSUE THREAD

**Issue by jbpros** [SmartBear/react-gherkin-editor#22]
We (Gherkin editor team) currently parse the gherkin document in our own code. That means for every keystroke in the document, two passes of the parser happen (one in gherkin editor, one in react-gherkin-editor). We'd like to rely on react-gherkin-editor to do the work, hence the request for a new prop looking like this:

```typescript
onGherkinDocumentChange={(errors: GherkinParserError[], doc: GherkinDocument) => { /* ... */ }} 
```

**Comment by cbohiptest** [comment]
Jira issue [BDD-4]

**Comment by cbohiptest** [comment]
The property is available since https://github.com/SmartBear/react-gherkin-editor/commit/b8472cf486b0420a6a58b3f4d45808a57d4f2018
The property is named onParse (and not onGherkindocumentChange) and send back messages.
