### ISSUE TITLE
Gitleaks-Action v2 announcement

### ISSUE THREAD

**Issue by zricethezav** [SmartBear/react-gherkin-editor#652]
Hi folks,

I maintain gitleaks and we noticed that you are not pinning your gitleaks-action version, but rather [using gitleaks-action@master](https://github.com/SmartBear/react-gherkin-editor/blob/master/.github/workflows/secrets-scan.yml#L33) and wanted to give you a heads up that we are planning to merge v2 to master soon, which is a breaking update. See more details [here](https://github.com/gitleaks/gitleaks-action#-announcement). By the way, we think you'll love [v2's features](https://github.com/gitleaks/gitleaks-action#v2-benefits). Let us know if you have any questions!

cc @mcoqblin-hiptest (I see you have contributed to this workflow)

**Comment by mcoqblin-hiptest** [comment]
Hello,

Thank you very much for letting us know! I will fix our workflow to use the current version and let dependabot check for new official releases.
